
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for production deployment
// These will be set in Vercel's environment variables section
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://mbdnovnvxotkntxybgce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZG5vdm52eG90a250eHliZ2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjg5ODAsImV4cCI6MjA2NTUwNDk4MH0.dh92Ms4oxn9zw68pLKNdi8ZIlCrZyTkLjfOwp2jxrXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
